Repository fga-eps-mds/2021-1-hospitalar, pull requests merged in 2021-10, with the labels that each got.

#226 Doc/171 protótipo alta fidelidade c
  docs/assets/produtos/prototipos/prototipo_time_c/tela_gerenciador_avaliacao_alta_fidelidade.png
  docs/assets/produtos/prototipos/prototipo_time_c/tela_gerenciador_user_alta_fidelidade.png
  docs/assets/produtos/prototipos/prototipo_time_c/tela_menu_principal_alta_fidelidade.png
  docs/produto/protótipo_alta_fidelidade/protótipo_alta_fidelidade_timeC.md
Labels: Time C

#234 . #159 - Utilizando modelo atualizado de Avaliação da Main
  backend/models/Avaliacao/relatorio/printing.py
  backend/models/Avaliacao/relatorio/utils.py
  backend/models/Avaliacao/views.py
Labels: Time B

#236 [H18/H29] Cadastro e Recuperação de Dados pelo Front-end (Tela Nova Avaliação)
  backend/backend/api.py
  backend/backend/settings.py
  backend/models/Avaliacao/migrations/0001_initial.py
  backend/models/Avaliacao/models.py
  backend/models/Avaliacao/serializers.py
  backend/models/Configuracao/__init__.py
  backend/models/Configuracao/admin.py
  backend/models/Configuracao/apps.py
  backend/models/Configuracao/migrations/0001_initial.py
  backend/models/Configuracao/migrations/__init__.py
  backend/models/Configuracao/models.py
  backend/models/Configuracao/serializers.py
  backend/models/Configuracao/views.py
  frontend/.eslintrc.js
  frontend/public/App.css
  frontend/public/index.html
  frontend/src/components/GlobalComponents/DatePicker/index.tsx
  frontend/src/components/GlobalComponents/DatePicker/styles.ts
  frontend/src/pages/EditarItem/styles.ts
  frontend/src/pages/NovaAvaliacao/index.tsx
  frontend/src/pages/PaginaAvaliacao/index.tsx
  frontend/src/theme/index.ts
  frontend/src/types/Avaliacao.ts
  frontend/yarn.lock
Labels: Time B, Desenvolvedor, Feature

#238 Pré visualizar
  frontend/.eslintrc.js
  frontend/src/pages/PreVisualizarRelatorio/index.tsx
  frontend/src/pages/PreVisualizarRelatorio/styles.ts
  frontend/src/routes.tsx
Labels: Time B, Desenvolvedor, Feature
